config/routes.rb
Rails.application.routes.draw do
  root 'user#index'

  resources :user do
  	collection do
      get :login_user
    end		
  end

  resources :bookings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	 serialize :item_id, Array
	#has_many :items
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/item.rb
class Item < ApplicationRecord
	#belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
	 validates :username, presence: true
	 validates :email, presence: true, :uniqueness => true
	 validates :password, presence: true
	 validates :user_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user	

  def current_user
    @current_user_id ||= User.find_by(id: session['user_id']) if session['user_id']
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   
  def index
   @item = Item.all
  end

  def new
    @booking = Booking.new
  end

  def create
    binding.pry
    @booking = Booking.new(booking_params)
    if @booking.save

      redirect_to bookings_path, notice: "Booking created"
    else
      render 'new' ,alert: "Something went wrong"
    end
  end	

  private
    def booking_params
      params.require(:booking).permit(:status,:item_id => [])
    end 
end

app/controllers/user_controller.rb
class UserController < ApplicationController        

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      binding.pry
      redirect_to user_index_path
    else
      render 'new'
    end
  end

  def login_user
    if params[:email].present? && params[:password].present? 
      user = User.where(email: params[:email], password: params[:password])
      unless user.blank?
        binding.pry
        session['user_id'] = user.ids
        redirect_to new_booking_path, notice: "You have successfully logged in"
      end
    end
  end  

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password, :user_type)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper	
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bookings/index.html.erb
<h1>Items Booked</h1>

<table>
  <tr>
    <th>Item</th>
  </tr>
  <%@item.each do |item|%>
  <tr>
    <td><%=item.item_type%></td>
  </tr>
  <%end%>
</table>

app/views/bookings/new.html.erb
<h1>Booking</h1>
<%= form_for @booking do |form| %>

 <p>
    <b>Choose your clothes</b><br />


 <%= form.collection_select(:item_id, Item.all, :id, :item_type, {:prompt => "Please Select your clothings"}, {:multiple => true}) %>

 <%= form.hidden_field :status, value: "confirm" %>
  </p>
  	<%= form.submit :book %>

  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DryCleaner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if flash[:notice]%>
    <div class="notice"><%=notice%></div>
  <%end%>
    <%if flash[:alert]%>
    <div class="alert"><%=alert%></div>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<%unless  @current_user_id.present? %>
<%= link_to "SIGNUP", new_user_path %>/<%= link_to "LOGIN", login_user_user_index_path %>
<%end%>
<%if  @current_user_id.present?%>
<%=link_to "LOGOUT",login_user_user_index_path%>
<%end%>

app/views/user/login_user.html.erb
<h1>LOGIN</h1>
 
<%=form_tag login_user_user_index_path, method: :get do %>
<p> 
  <%= label_tag  :email %>
  <%=text_field_tag :email%>
</p>
<p> 
  <%= label_tag  :password %>
  <%=password_field_tag :password%>
</p>

<p>
  <%=submit_tag :login%>
</p>
<%end%>

app/views/user/new.html.erb
<h1>SIGNUP</h1>
<%= form_with scope: :user, url: user_index_path, local: true do |form| %>
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>
 
  <p>   <%= form.label :user_type %><br>
        <%= form.select(:user_type, ["service provider","service taker"])%>
  </p>
  <p>
  	<%= form.submit %>

  </p>
<% end %>